import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

const skills = [
  // ========== FRONTEND ==========
  {
    id: 'skill_react',
    name: 'React',
    slug: 'react',
    category: 'Frontend',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg',
    aliases: ['ReactJS', 'React.js'],
    verified: true,
  },
  {
    id: 'skill_vue',
    name: 'Vue.js',
    slug: 'vue',
    category: 'Frontend',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/vuejs/vuejs-original.svg',
    aliases: ['Vue', 'VueJS', 'Vue 3'],
    verified: true,
  },
  {
    id: 'skill_angular',
    name: 'Angular',
    slug: 'angular',
    category: 'Frontend',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/angularjs/angularjs-original.svg',
    aliases: ['AngularJS', 'Angular 2+'],
    verified: true,
  },
  {
    id: 'skill_nextjs',
    name: 'Next.js',
    slug: 'nextjs',
    category: 'Frontend',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nextjs/nextjs-original.svg',
    aliases: ['Next', 'NextJS'],
    verified: true,
  },
  {
    id: 'skill_svelte',
    name: 'Svelte',
    slug: 'svelte',
    category: 'Frontend',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/svelte/svelte-original.svg',
    aliases: ['SvelteJS'],
    verified: true,
  },
  {
    id: 'skill_css',
    name: 'CSS',
    slug: 'css',
    category: 'Frontend',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/css3/css3-original.svg',
    aliases: ['CSS3'],
    verified: true,
  },
  {
    id: 'skill_html',
    name: 'HTML',
    slug: 'html',
    category: 'Frontend',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/html5/html5-original.svg',
    aliases: ['HTML5'],
    verified: true,
  },
  {
    id: 'skill_tailwind',
    name: 'Tailwind CSS',
    slug: 'tailwind',
    category: 'Frontend',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/tailwindcss/tailwindcss-plain.svg',
    aliases: ['TailwindCSS'],
    verified: true,
  },
  {
    id: 'skill_sass',
    name: 'Sass',
    slug: 'sass',
    category: 'Frontend',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/sass/sass-original.svg',
    aliases: ['SCSS'],
    verified: true,
  },
  {
    id: 'skill_solidjs',
    name: 'Solid.js',
    slug: 'solidjs',
    category: 'Frontend',
    logoUrl: null,
    aliases: ['SolidJS', 'Solid'],
    verified: true,
  },
  {
    id: 'skill_alpine',
    name: 'Alpine.js',
    slug: 'alpinejs',
    category: 'Frontend',
    logoUrl: null,
    aliases: ['Alpine'],
    verified: true,
  },
  {
    id: 'skill_qwik',
    name: 'Qwik',
    slug: 'qwik',
    category: 'Frontend',
    logoUrl: null,
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_lit',
    name: 'Lit',
    slug: 'lit',
    category: 'Frontend',
    logoUrl: null,
    aliases: ['LitElement'],
    verified: true,
  },
  {
    id: 'skill_preact',
    name: 'Preact',
    slug: 'preact',
    category: 'Frontend',
    logoUrl: null,
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_ember',
    name: 'Ember.js',
    slug: 'emberjs',
    category: 'Frontend',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/ember/ember-original.svg',
    aliases: ['Ember'],
    verified: true,
  },
  {
    id: 'skill_nuxtjs',
    name: 'Nuxt.js',
    slug: 'nuxtjs',
    category: 'Frontend',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nuxtjs/nuxtjs-original.svg',
    aliases: ['Nuxt'],
    verified: true,
  },
  {
    id: 'skill_gatsby',
    name: 'Gatsby',
    slug: 'gatsby',
    category: 'Frontend',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/gatsby/gatsby-original.svg',
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_remix',
    name: 'Remix',
    slug: 'remix',
    category: 'Frontend',
    logoUrl: null,
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_astro',
    name: 'Astro',
    slug: 'astro',
    category: 'Frontend',
    logoUrl: null,
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_sveltekit',
    name: 'SvelteKit',
    slug: 'sveltekit',
    category: 'Frontend',
    logoUrl: null,
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_backbone',
    name: 'Backbone.js',
    slug: 'backbonejs',
    category: 'Frontend',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/backbonejs/backbonejs-original.svg',
    aliases: ['Backbone'],
    verified: false,
  },
  {
    id: 'skill_less',
    name: 'Less',
    slug: 'less',
    category: 'Frontend',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/less/less-plain-wordmark.svg',
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_bootstrap',
    name: 'Bootstrap',
    slug: 'bootstrap',
    category: 'Frontend',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/bootstrap/bootstrap-original.svg',
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_postcss',
    name: 'PostCSS',
    slug: 'postcss',
    category: 'Frontend',
    logoUrl: null,
    aliases: [],
    verified: true,
  },
  // ========== BACKEND ==========
  {
    id: 'skill_nodejs',
    name: 'Node.js',
    slug: 'nodejs',
    category: 'Backend',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nodejs/nodejs-original.svg',
    aliases: ['Node', 'NodeJS'],
    verified: true,
  },
  {
    id: 'skill_express',
    name: 'Express.js',
    slug: 'express',
    category: 'Backend',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/express/express-original.svg',
    aliases: ['Express', 'ExpressJS'],
    verified: true,
  },
  {
    id: 'skill_nestjs',
    name: 'NestJS',
    slug: 'nestjs',
    category: 'Backend',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nestjs/nestjs-plain.svg',
    aliases: ['Nest', 'Nest.js'],
    verified: true,
  },
  {
    id: 'skill_fastify',
    name: 'Fastify',
    slug: 'fastify',
    category: 'Backend',
    logoUrl: null,
    aliases: ['Fastify.js'],
    verified: true,
  },
  {
    id: 'skill_koa',
    name: 'Koa.js',
    slug: 'koa',
    category: 'Backend',
    logoUrl: null,
    aliases: ['Koa', 'KoaJS'],
    verified: true,
  },
  {
    id: 'skill_hapi',
    name: 'Hapi.js',
    slug: 'hapi',
    category: 'Backend',
    logoUrl: null,
    aliases: ['Hapi', 'HapiJS'],
    verified: true,
  },
  {
    id: 'skill_django',
    name: 'Django',
    slug: 'django',
    category: 'Backend',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/django/django-plain.svg',
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_flask',
    name: 'Flask',
    slug: 'flask',
    category: 'Backend',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/flask/flask-original.svg',
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_fastapi',
    name: 'FastAPI',
    slug: 'fastapi',
    category: 'Backend',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/fastapi/fastapi-original.svg',
    aliases: ['Fast API'],
    verified: true,
  },
  {
    id: 'skill_spring',
    name: 'Spring Boot',
    slug: 'spring-boot',
    category: 'Backend',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/spring/spring-original.svg',
    aliases: ['SpringBoot', 'Spring Framework'],
    verified: true,
  },
  {
    id: 'skill_dotnet',
    name: '.NET Core',
    slug: 'dotnet-core',
    category: 'Backend',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/dotnetcore/dotnetcore-original.svg',
    aliases: ['ASP.NET Core', '.NET 6+', '.NET'],
    verified: true,
  },
  {
    id: 'skill_laravel',
    name: 'Laravel',
    slug: 'laravel',
    category: 'Backend',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/laravel/laravel-plain.svg',
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_symfony',
    name: 'Symfony',
    slug: 'symfony',
    category: 'Backend',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/symfony/symfony-original.svg',
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_rails',
    name: 'Ruby on Rails',
    slug: 'rails',
    category: 'Backend',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/rails/rails-original-wordmark.svg',
    aliases: ['Rails', 'RoR'],
    verified: true,
  },
  {
    id: 'skill_phoenix',
    name: 'Phoenix',
    slug: 'phoenix',
    category: 'Backend',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/phoenix/phoenix-original.svg',
    aliases: ['Phoenix Framework'],
    verified: true,
  },
  {
    id: 'skill_gin',
    name: 'Gin',
    slug: 'gin',
    category: 'Backend',
    logoUrl: null,
    aliases: ['Gin-Gonic'],
    verified: true,
  },
  {
    id: 'skill_echo',
    name: 'Echo',
    slug: 'echo',
    category: 'Backend',
    logoUrl: null,
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_fiber',
    name: 'Fiber',
    slug: 'fiber',
    category: 'Backend',
    logoUrl: null,
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_actix',
    name: 'Actix',
    slug: 'actix',
    category: 'Backend',
    logoUrl: null,
    aliases: ['Actix-Web'],
    verified: true,
  },
  // ========== LANGUAGES ==========
  {
    id: 'skill_javascript',
    name: 'JavaScript',
    slug: 'javascript',
    category: 'Language',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/javascript/javascript-original.svg',
    aliases: ['JS', 'ECMAScript'],
    verified: true,
  },
  {
    id: 'skill_typescript',
    name: 'TypeScript',
    slug: 'typescript',
    category: 'Language',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/typescript/typescript-original.svg',
    aliases: ['TS'],
    verified: true,
  },
  {
    id: 'skill_python',
    name: 'Python',
    slug: 'python',
    category: 'Language',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/python/python-original.svg',
    aliases: ['Python3', 'py'],
    verified: true,
  },
  {
    id: 'skill_java',
    name: 'Java',
    slug: 'java',
    category: 'Language',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/java/java-original.svg',
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_csharp',
    name: 'C#',
    slug: 'csharp',
    category: 'Language',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/csharp/csharp-original.svg',
    aliases: ['C Sharp', 'CSharp', 'C-Sharp'],
    verified: true,
  },
  {
    id: 'skill_go',
    name: 'Go',
    slug: 'go',
    category: 'Language',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/go/go-original.svg',
    aliases: ['Golang'],
    verified: true,
  },
  {
    id: 'skill_rust',
    name: 'Rust',
    slug: 'rust',
    category: 'Language',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/rust/rust-plain.svg',
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_php',
    name: 'PHP',
    slug: 'php',
    category: 'Language',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/php/php-original.svg',
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_cpp',
    name: 'C++',
    slug: 'cpp',
    category: 'Language',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/cplusplus/cplusplus-original.svg',
    aliases: ['CPlusPlus', 'Cpp'],
    verified: true,
  },
  {
    id: 'skill_c',
    name: 'C',
    slug: 'c',
    category: 'Language',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/c/c-original.svg',
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_swift',
    name: 'Swift',
    slug: 'swift',
    category: 'Language',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/swift/swift-original.svg',
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_kotlin',
    name: 'Kotlin',
    slug: 'kotlin',
    category: 'Language',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/kotlin/kotlin-original.svg',
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_ruby',
    name: 'Ruby',
    slug: 'ruby',
    category: 'Language',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/ruby/ruby-original.svg',
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_scala',
    name: 'Scala',
    slug: 'scala',
    category: 'Language',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/scala/scala-original.svg',
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_elixir',
    name: 'Elixir',
    slug: 'elixir',
    category: 'Language',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/elixir/elixir-original.svg',
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_erlang',
    name: 'Erlang',
    slug: 'erlang',
    category: 'Language',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/erlang/erlang-original.svg',
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_clojure',
    name: 'Clojure',
    slug: 'clojure',
    category: 'Language',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/clojure/clojure-original.svg',
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_haskell',
    name: 'Haskell',
    slug: 'haskell',
    category: 'Language',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/haskell/haskell-original.svg',
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_fsharp',
    name: 'F#',
    slug: 'fsharp',
    category: 'Language',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/fsharp/fsharp-original.svg',
    aliases: ['FSharp'],
    verified: true,
  },
  {
    id: 'skill_dart',
    name: 'Dart',
    slug: 'dart',
    category: 'Language',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/dart/dart-original.svg',
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_julia',
    name: 'Julia',
    slug: 'julia',
    category: 'Language',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/julia/julia-original.svg',
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_r',
    name: 'R',
    slug: 'r',
    category: 'Language',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/r/r-original.svg',
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_matlab',
    name: 'MATLAB',
    slug: 'matlab',
    category: 'Language',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/matlab/matlab-original.svg',
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_zig',
    name: 'Zig',
    slug: 'zig',
    category: 'Language',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/zig/zig-original.svg',
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_ocaml',
    name: 'OCaml',
    slug: 'ocaml',
    category: 'Language',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/ocaml/ocaml-original.svg',
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_objectivec',
    name: 'Objective-C',
    slug: 'objectivec',
    category: 'Language',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/objectivec/objectivec-plain.svg',
    aliases: ['ObjC'],
    verified: true,
  },
  {
    id: 'skill_perl',
    name: 'Perl',
    slug: 'perl',
    category: 'Language',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/perl/perl-original.svg',
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_lua',
    name: 'Lua',
    slug: 'lua',
    category: 'Language',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/lua/lua-original.svg',
    aliases: [],
    verified: true,
  },
  // ========== DATABASES ==========
  {
    id: 'skill_mysql',
    name: 'MySQL',
    slug: 'mysql',
    category: 'Database',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mysql/mysql-original.svg',
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_postgresql',
    name: 'PostgreSQL',
    slug: 'postgresql',
    category: 'Database',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/postgresql/postgresql-original.svg',
    aliases: ['Postgres'],
    verified: true,
  },
  {
    id: 'skill_mongodb',
    name: 'MongoDB',
    slug: 'mongodb',
    category: 'Database',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mongodb/mongodb-original.svg',
    aliases: ['Mongo'],
    verified: true,
  },
  {
    id: 'skill_redis',
    name: 'Redis',
    slug: 'redis',
    category: 'Database',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/redis/redis-original.svg',
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_sqlite',
    name: 'SQLite',
    slug: 'sqlite',
    category: 'Database',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/sqlite/sqlite-original.svg',
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_mariadb',
    name: 'MariaDB',
    slug: 'mariadb',
    category: 'Database',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mariadb/mariadb-original.svg',
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_sqlserver',
    name: 'Microsoft SQL Server',
    slug: 'sql-server',
    category: 'Database',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/microsoftsqlserver/microsoftsqlserver-plain.svg',
    aliases: ['MSSQL', 'SQL Server'],
    verified: true,
  },
  {
    id: 'skill_oracle',
    name: 'Oracle',
    slug: 'oracle',
    category: 'Database',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/oracle/oracle-original.svg',
    aliases: ['Oracle Database'],
    verified: true,
  },
  {
    id: 'skill_dynamodb',
    name: 'DynamoDB',
    slug: 'dynamodb',
    category: 'Database',
    logoUrl: null,
    aliases: ['Amazon DynamoDB', 'AWS DynamoDB'],
    verified: true,
  },
  {
    id: 'skill_cassandra',
    name: 'Cassandra',
    slug: 'cassandra',
    category: 'Database',
    logoUrl: null,
    aliases: ['Apache Cassandra'],
    verified: true,
  },
  {
    id: 'skill_elasticsearch',
    name: 'Elasticsearch',
    slug: 'elasticsearch',
    category: 'Database',
    logoUrl: null,
    aliases: ['Elastic'],
    verified: true,
  },
  {
    id: 'skill_neo4j',
    name: 'Neo4j',
    slug: 'neo4j',
    category: 'Database',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/neo4j/neo4j-original.svg',
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_couchdb',
    name: 'CouchDB',
    slug: 'couchdb',
    category: 'Database',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/couchdb/couchdb-original.svg',
    aliases: ['Apache CouchDB'],
    verified: true,
  },
  {
    id: 'skill_firestore',
    name: 'Firebase Firestore',
    slug: 'firestore',
    category: 'Database',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/firebase/firebase-plain.svg',
    aliases: ['Firestore'],
    verified: true,
  },
  {
    id: 'skill_supabase',
    name: 'Supabase',
    slug: 'supabase',
    category: 'Database',
    logoUrl: null,
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_cockroachdb',
    name: 'CockroachDB',
    slug: 'cockroachdb',
    category: 'Database',
    logoUrl: null,
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_planetscale',
    name: 'PlanetScale',
    slug: 'planetscale',
    category: 'Database',
    logoUrl: null,
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_faunadb',
    name: 'FaunaDB',
    slug: 'faunadb',
    category: 'Database',
    logoUrl: null,
    aliases: ['Fauna'],
    verified: true,
  },
  {
    id: 'skill_cosmosdb',
    name: 'Azure Cosmos DB',
    slug: 'cosmosdb',
    category: 'Database',
    logoUrl: null,
    aliases: ['CosmosDB', 'Cosmos DB'],
    verified: true,
  },
  {
    id: 'skill_arangodb',
    name: 'ArangoDB',
    slug: 'arangodb',
    category: 'Database',
    logoUrl: null,
    aliases: [],
    verified: true,
  },
  // ========== CLOUD & DEVOPS ==========
  {
    id: 'skill_aws',
    name: 'AWS',
    slug: 'aws',
    category: 'Cloud',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/amazonwebservices/amazonwebservices-original.svg',
    aliases: ['Amazon Web Services'],
    verified: true,
  },
  {
    id: 'skill_gcp',
    name: 'Google Cloud',
    slug: 'gcp',
    category: 'Cloud',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/googlecloud/googlecloud-original.svg',
    aliases: ['GCP', 'Google Cloud Platform'],
    verified: true,
  },
  {
    id: 'skill_azure',
    name: 'Azure',
    slug: 'azure',
    category: 'Cloud',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/azure/azure-original.svg',
    aliases: ['Microsoft Azure'],
    verified: true,
  },
  {
    id: 'skill_docker',
    name: 'Docker',
    slug: 'docker',
    category: 'DevOps',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/docker/docker-original.svg',
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_kubernetes',
    name: 'Kubernetes',
    slug: 'kubernetes',
    category: 'DevOps',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/kubernetes/kubernetes-plain.svg',
    aliases: ['K8s'],
    verified: true,
  },
  {
    id: 'skill_terraform',
    name: 'Terraform',
    slug: 'terraform',
    category: 'DevOps',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/terraform/terraform-original.svg',
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_vercel',
    name: 'Vercel',
    slug: 'vercel',
    category: 'Cloud',
    logoUrl: null,
    aliases: ['zeit-now', 'Now'],
    verified: true,
  },
  {
    id: 'skill_netlify',
    name: 'Netlify',
    slug: 'netlify',
    category: 'Cloud',
    logoUrl: null,
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_heroku',
    name: 'Heroku',
    slug: 'heroku',
    category: 'Cloud',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/heroku/heroku-original.svg',
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_digitalocean',
    name: 'DigitalOcean',
    slug: 'digitalocean',
    category: 'Cloud',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/digitalocean/digitalocean-original.svg',
    aliases: ['DO'],
    verified: true,
  },
  {
    id: 'skill_cloudflare',
    name: 'Cloudflare',
    slug: 'cloudflare',
    category: 'Cloud',
    logoUrl: null,
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_jenkins',
    name: 'Jenkins',
    slug: 'jenkins',
    category: 'DevOps',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/jenkins/jenkins-original.svg',
    aliases: ['Jenkins CI'],
    verified: true,
  },
  {
    id: 'skill_ansible',
    name: 'Ansible',
    slug: 'ansible',
    category: 'DevOps',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/ansible/ansible-original.svg',
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_prometheus',
    name: 'Prometheus',
    slug: 'prometheus',
    category: 'DevOps',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/prometheus/prometheus-original.svg',
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_grafana',
    name: 'Grafana',
    slug: 'grafana',
    category: 'DevOps',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/grafana/grafana-original.svg',
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_circleci',
    name: 'CircleCI',
    slug: 'circleci',
    category: 'DevOps',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/circleci/circleci-plain.svg',
    aliases: ['Circle CI'],
    verified: true,
  },
  {
    id: 'skill_githubactions',
    name: 'GitHub Actions',
    slug: 'github-actions',
    category: 'DevOps',
    logoUrl: null,
    aliases: ['Actions', 'GH Actions'],
    verified: true,
  },
  {
    id: 'skill_gitlabci',
    name: 'GitLab CI',
    slug: 'gitlab-ci',
    category: 'DevOps',
    logoUrl: null,
    aliases: ['GitLab CI/CD'],
    verified: true,
  },
  {
    id: 'skill_argocd',
    name: 'ArgoCD',
    slug: 'argocd',
    category: 'DevOps',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/argocd/argocd-original.svg',
    aliases: ['Argo CD'],
    verified: true,
  },
  {
    id: 'skill_pulumi',
    name: 'Pulumi',
    slug: 'pulumi',
    category: 'DevOps',
    logoUrl: null,
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_puppet',
    name: 'Puppet',
    slug: 'puppet',
    category: 'DevOps',
    logoUrl: null,
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_chef',
    name: 'Chef',
    slug: 'chef',
    category: 'DevOps',
    logoUrl: null,
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_travisci',
    name: 'Travis CI',
    slug: 'travis-ci',
    category: 'DevOps',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/travis/travis-plain.svg',
    aliases: ['Travis'],
    verified: true,
  },
  {
    id: 'skill_azuredevops',
    name: 'Azure DevOps',
    slug: 'azure-devops',
    category: 'DevOps',
    logoUrl: null,
    aliases: ['Azure Pipelines'],
    verified: true,
  },
  {
    id: 'skill_datadog',
    name: 'Datadog',
    slug: 'datadog',
    category: 'DevOps',
    logoUrl: null,
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_newrelic',
    name: 'New Relic',
    slug: 'newrelic',
    category: 'DevOps',
    logoUrl: null,
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_splunk',
    name: 'Splunk',
    slug: 'splunk',
    category: 'DevOps',
    logoUrl: null,
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_sentry',
    name: 'Sentry',
    slug: 'sentry',
    category: 'DevOps',
    logoUrl: null,
    aliases: [],
    verified: true,
  },
  // ========== TOOLS ==========
  {
    id: 'skill_git',
    name: 'Git',
    slug: 'git',
    category: 'Tool',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/git/git-original.svg',
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_github',
    name: 'GitHub',
    slug: 'github',
    category: 'Tool',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/github/github-original.svg',
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_gitlab',
    name: 'GitLab',
    slug: 'gitlab',
    category: 'Tool',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/gitlab/gitlab-original.svg',
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_vscode',
    name: 'VS Code',
    slug: 'vscode',
    category: 'Tool',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/vscode/vscode-original.svg',
    aliases: ['Visual Studio Code', 'VSCode'],
    verified: true,
  },
  {
    id: 'skill_vite',
    name: 'Vite',
    slug: 'vite',
    category: 'Tool',
    logoUrl: null,
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_webpack',
    name: 'Webpack',
    slug: 'webpack',
    category: 'Tool',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/webpack/webpack-original.svg',
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_babel',
    name: 'Babel',
    slug: 'babel',
    category: 'Tool',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/babel/babel-original.svg',
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_npm',
    name: 'npm',
    slug: 'npm',
    category: 'Tool',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/npm/npm-original-wordmark.svg',
    aliases: ['Node Package Manager'],
    verified: true,
  },
  {
    id: 'skill_yarn',
    name: 'Yarn',
    slug: 'yarn',
    category: 'Tool',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/yarn/yarn-original.svg',
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_pnpm',
    name: 'pnpm',
    slug: 'pnpm',
    category: 'Tool',
    logoUrl: null,
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_rollup',
    name: 'Rollup',
    slug: 'rollup',
    category: 'Tool',
    logoUrl: null,
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_parcel',
    name: 'Parcel',
    slug: 'parcel',
    category: 'Tool',
    logoUrl: null,
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_esbuild',
    name: 'esbuild',
    slug: 'esbuild',
    category: 'Tool',
    logoUrl: null,
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_swc',
    name: 'SWC',
    slug: 'swc',
    category: 'Tool',
    logoUrl: null,
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_nx',
    name: 'Nx',
    slug: 'nx',
    category: 'Tool',
    logoUrl: null,
    aliases: ['Nx.dev'],
    verified: true,
  },
  {
    id: 'skill_turborepo',
    name: 'Turborepo',
    slug: 'turborepo',
    category: 'Tool',
    logoUrl: null,
    aliases: ['Turbo'],
    verified: true,
  },
  {
    id: 'skill_lerna',
    name: 'Lerna',
    slug: 'lerna',
    category: 'Tool',
    logoUrl: null,
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_maven',
    name: 'Maven',
    slug: 'maven',
    category: 'Tool',
    logoUrl: null,
    aliases: ['Apache Maven'],
    verified: true,
  },
  {
    id: 'skill_gradle',
    name: 'Gradle',
    slug: 'gradle',
    category: 'Tool',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/gradle/gradle-plain.svg',
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_cargo',
    name: 'Cargo',
    slug: 'cargo',
    category: 'Tool',
    logoUrl: null,
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_pip',
    name: 'pip',
    slug: 'pip',
    category: 'Tool',
    logoUrl: null,
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_poetry',
    name: 'Poetry',
    slug: 'poetry',
    category: 'Tool',
    logoUrl: null,
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_composer',
    name: 'Composer',
    slug: 'composer',
    category: 'Tool',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/composer/composer-original.svg',
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_bitbucket',
    name: 'Bitbucket',
    slug: 'bitbucket',
    category: 'Tool',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/bitbucket/bitbucket-original.svg',
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_intellij',
    name: 'IntelliJ IDEA',
    slug: 'intellij',
    category: 'Tool',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/intellij/intellij-original.svg',
    aliases: ['IntelliJ'],
    verified: true,
  },
  {
    id: 'skill_webstorm',
    name: 'WebStorm',
    slug: 'webstorm',
    category: 'Tool',
    logoUrl: null,
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_visualstudio',
    name: 'Visual Studio',
    slug: 'visualstudio',
    category: 'Tool',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/visualstudio/visualstudio-plain.svg',
    aliases: ['VS'],
    verified: true,
  },
  // ========== TESTING ==========
  {
    id: 'skill_jest',
    name: 'Jest',
    slug: 'jest',
    category: 'Testing',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/jest/jest-plain.svg',
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_cypress',
    name: 'Cypress',
    slug: 'cypress',
    category: 'Testing',
    logoUrl: null,
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_playwright',
    name: 'Playwright',
    slug: 'playwright',
    category: 'Testing',
    logoUrl: null,
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_selenium',
    name: 'Selenium',
    slug: 'selenium',
    category: 'Testing',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/selenium/selenium-original.svg',
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_mocha',
    name: 'Mocha',
    slug: 'mocha',
    category: 'Testing',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mocha/mocha-plain.svg',
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_chai',
    name: 'Chai',
    slug: 'chai',
    category: 'Testing',
    logoUrl: null,
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_jasmine',
    name: 'Jasmine',
    slug: 'jasmine',
    category: 'Testing',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/jasmine/jasmine-plain.svg',
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_puppeteer',
    name: 'Puppeteer',
    slug: 'puppeteer',
    category: 'Testing',
    logoUrl: null,
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_testcafe',
    name: 'TestCafe',
    slug: 'testcafe',
    category: 'Testing',
    logoUrl: null,
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_webdriverio',
    name: 'WebdriverIO',
    slug: 'webdriverio',
    category: 'Testing',
    logoUrl: null,
    aliases: ['WDIO'],
    verified: true,
  },
  {
    id: 'skill_junit',
    name: 'JUnit',
    slug: 'junit',
    category: 'Testing',
    logoUrl: null,
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_pytest',
    name: 'pytest',
    slug: 'pytest',
    category: 'Testing',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/pytest/pytest-original.svg',
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_rspec',
    name: 'RSpec',
    slug: 'rspec',
    category: 'Testing',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/rspec/rspec-original.svg',
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_phpunit',
    name: 'PHPUnit',
    slug: 'phpunit',
    category: 'Testing',
    logoUrl: null,
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_vitest',
    name: 'Vitest',
    slug: 'vitest',
    category: 'Testing',
    logoUrl: null,
    aliases: [],
    verified: true,
  },
  // ========== STATE MANAGEMENT ==========
  {
    id: 'skill_redux',
    name: 'Redux',
    slug: 'redux',
    category: 'State Management',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/redux/redux-original.svg',
    aliases: ['Redux Toolkit', 'RTK'],
    verified: true,
  },
  {
    id: 'skill_mobx',
    name: 'MobX',
    slug: 'mobx',
    category: 'State Management',
    logoUrl: null,
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_zustand',
    name: 'Zustand',
    slug: 'zustand',
    category: 'State Management',
    logoUrl: null,
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_pinia',
    name: 'Pinia',
    slug: 'pinia',
    category: 'State Management',
    logoUrl: null,
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_vuex',
    name: 'Vuex',
    slug: 'vuex',
    category: 'State Management',
    logoUrl: null,
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_recoil',
    name: 'Recoil',
    slug: 'recoil',
    category: 'State Management',
    logoUrl: null,
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_jotai',
    name: 'Jotai',
    slug: 'jotai',
    category: 'State Management',
    logoUrl: null,
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_xstate',
    name: 'XState',
    slug: 'xstate',
    category: 'State Management',
    logoUrl: null,
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_valtio',
    name: 'Valtio',
    slug: 'valtio',
    category: 'State Management',
    logoUrl: null,
    aliases: [],
    verified: true,
  },
  // ========== API & ORM ==========
  {
    id: 'skill_graphql',
    name: 'GraphQL',
    slug: 'graphql',
    category: 'API',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/graphql/graphql-plain.svg',
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_rest',
    name: 'REST',
    slug: 'rest',
    category: 'API',
    logoUrl: null,
    aliases: ['RESTful', 'REST API'],
    verified: true,
  },
  {
    id: 'skill_grpc',
    name: 'gRPC',
    slug: 'grpc',
    category: 'API',
    logoUrl: null,
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_apolloserver',
    name: 'Apollo Server',
    slug: 'apollo-server',
    category: 'API',
    logoUrl: null,
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_apolloclient',
    name: 'Apollo Client',
    slug: 'apollo-client',
    category: 'API',
    logoUrl: null,
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_postman',
    name: 'Postman',
    slug: 'postman',
    category: 'API',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/postman/postman-original.svg',
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_insomnia',
    name: 'Insomnia',
    slug: 'insomnia',
    category: 'API',
    logoUrl: null,
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_swagger',
    name: 'Swagger',
    slug: 'swagger',
    category: 'API',
    logoUrl: null,
    aliases: ['OpenAPI'],
    verified: true,
  },
  {
    id: 'skill_prisma',
    name: 'Prisma',
    slug: 'prisma',
    category: 'ORM',
    logoUrl: null,
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_typeorm',
    name: 'TypeORM',
    slug: 'typeorm',
    category: 'ORM',
    logoUrl: null,
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_sequelize',
    name: 'Sequelize',
    slug: 'sequelize',
    category: 'ORM',
    logoUrl: null,
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_mongoose',
    name: 'Mongoose',
    slug: 'mongoose',
    category: 'ORM',
    logoUrl: null,
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_drizzle',
    name: 'Drizzle',
    slug: 'drizzle',
    category: 'ORM',
    logoUrl: null,
    aliases: ['Drizzle ORM'],
    verified: true,
  },
  // ========== UI LIBRARIES ==========
  {
    id: 'skill_materialui',
    name: 'Material-UI',
    slug: 'material-ui',
    category: 'UI Library',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/materialui/materialui-original.svg',
    aliases: ['MUI'],
    verified: true,
  },
  {
    id: 'skill_antdesign',
    name: 'Ant Design',
    slug: 'ant-design',
    category: 'UI Library',
    logoUrl: null,
    aliases: ['AntD'],
    verified: true,
  },
  {
    id: 'skill_chakraui',
    name: 'Chakra UI',
    slug: 'chakra-ui',
    category: 'UI Library',
    logoUrl: null,
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_shadcnui',
    name: 'shadcn/ui',
    slug: 'shadcn-ui',
    category: 'UI Library',
    logoUrl: null,
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_radixui',
    name: 'Radix UI',
    slug: 'radix-ui',
    category: 'UI Library',
    logoUrl: null,
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_headlessui',
    name: 'Headless UI',
    slug: 'headless-ui',
    category: 'UI Library',
    logoUrl: null,
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_mantine',
    name: 'Mantine',
    slug: 'mantine',
    category: 'UI Library',
    logoUrl: null,
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_vuetify',
    name: 'Vuetify',
    slug: 'vuetify',
    category: 'UI Library',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/vuetify/vuetify-original.svg',
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_primereact',
    name: 'PrimeReact',
    slug: 'primereact',
    category: 'UI Library',
    logoUrl: null,
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_bulma',
    name: 'Bulma',
    slug: 'bulma',
    category: 'UI Library',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/bulma/bulma-plain.svg',
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_semanticui',
    name: 'Semantic UI',
    slug: 'semantic-ui',
    category: 'UI Library',
    logoUrl: null,
    aliases: [],
    verified: true,
  },
  // ========== MOBILE ==========
  {
    id: 'skill_reactnative',
    name: 'React Native',
    slug: 'react-native',
    category: 'Mobile',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg',
    aliases: ['RN'],
    verified: true,
  },
  {
    id: 'skill_flutter',
    name: 'Flutter',
    slug: 'flutter',
    category: 'Mobile',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/flutter/flutter-original.svg',
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_ionic',
    name: 'Ionic',
    slug: 'ionic',
    category: 'Mobile',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/ionic/ionic-original.svg',
    aliases: ['Ionic Framework'],
    verified: true,
  },
  {
    id: 'skill_xamarin',
    name: 'Xamarin',
    slug: 'xamarin',
    category: 'Mobile',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/xamarin/xamarin-original.svg',
    aliases: ['Microsoft Xamarin'],
    verified: true,
  },
  {
    id: 'skill_swiftui',
    name: 'SwiftUI',
    slug: 'swiftui',
    category: 'Mobile',
    logoUrl: null,
    aliases: ['Apple SwiftUI'],
    verified: true,
  },
  {
    id: 'skill_jetpackcompose',
    name: 'Jetpack Compose',
    slug: 'jetpack-compose',
    category: 'Mobile',
    logoUrl: null,
    aliases: ['Android Compose'],
    verified: true,
  },
  {
    id: 'skill_expo',
    name: 'Expo',
    slug: 'expo',
    category: 'Mobile',
    logoUrl: null,
    aliases: ['Expo SDK'],
    verified: true,
  },
  {
    id: 'skill_nativescript',
    name: 'NativeScript',
    slug: 'nativescript',
    category: 'Mobile',
    logoUrl: null,
    aliases: ['NS'],
    verified: true,
  },
  {
    id: 'skill_capacitor',
    name: 'Capacitor',
    slug: 'capacitor',
    category: 'Mobile',
    logoUrl: null,
    aliases: ['Ionic Capacitor'],
    verified: true,
  },
  // ========== AI/ML ==========
  {
    id: 'skill_tensorflow',
    name: 'TensorFlow',
    slug: 'tensorflow',
    category: 'AI/ML',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/tensorflow/tensorflow-original.svg',
    aliases: ['TF'],
    verified: true,
  },
  {
    id: 'skill_pytorch',
    name: 'PyTorch',
    slug: 'pytorch',
    category: 'AI/ML',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/pytorch/pytorch-original.svg',
    aliases: ['Torch'],
    verified: true,
  },
  {
    id: 'skill_scikitlearn',
    name: 'scikit-learn',
    slug: 'scikit-learn',
    category: 'AI/ML',
    logoUrl: null,
    aliases: ['sklearn'],
    verified: true,
  },
  {
    id: 'skill_keras',
    name: 'Keras',
    slug: 'keras',
    category: 'AI/ML',
    logoUrl: null,
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_openai',
    name: 'OpenAI API',
    slug: 'openai',
    category: 'AI/ML',
    logoUrl: null,
    aliases: ['GPT API', 'ChatGPT API'],
    verified: true,
  },
  {
    id: 'skill_huggingface',
    name: 'Hugging Face',
    slug: 'huggingface',
    category: 'AI/ML',
    logoUrl: null,
    aliases: ['HF Transformers'],
    verified: true,
  },
  {
    id: 'skill_langchain',
    name: 'LangChain',
    slug: 'langchain',
    category: 'AI/ML',
    logoUrl: null,
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_pandas',
    name: 'pandas',
    slug: 'pandas',
    category: 'AI/ML',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/pandas/pandas-original.svg',
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_numpy',
    name: 'NumPy',
    slug: 'numpy',
    category: 'AI/ML',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/numpy/numpy-original.svg',
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_jupyter',
    name: 'Jupyter',
    slug: 'jupyter',
    category: 'AI/ML',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/jupyter/jupyter-original.svg',
    aliases: ['Jupyter Notebook'],
    verified: true,
  },
  // ========== MESSAGE QUEUES ==========
  {
    id: 'skill_kafka',
    name: 'Apache Kafka',
    slug: 'kafka',
    category: 'Message Queue',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/apachekafka/apachekafka-original.svg',
    aliases: ['Kafka'],
    verified: true,
  },
  {
    id: 'skill_rabbitmq',
    name: 'RabbitMQ',
    slug: 'rabbitmq',
    category: 'Message Queue',
    logoUrl: null,
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_sqs',
    name: 'AWS SQS',
    slug: 'sqs',
    category: 'Message Queue',
    logoUrl: null,
    aliases: ['Amazon SQS'],
    verified: true,
  },
  {
    id: 'skill_pubsub',
    name: 'Google Pub/Sub',
    slug: 'pubsub',
    category: 'Message Queue',
    logoUrl: null,
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_nats',
    name: 'NATS',
    slug: 'nats',
    category: 'Message Queue',
    logoUrl: null,
    aliases: [],
    verified: true,
  },
  // ========== GAME DEVELOPMENT ==========
  {
    id: 'skill_unity',
    name: 'Unity',
    slug: 'unity',
    category: 'Game Development',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/unity/unity-original.svg',
    aliases: ['Unity3D', 'Unity Engine'],
    verified: true,
  },
  {
    id: 'skill_unrealengine',
    name: 'Unreal Engine',
    slug: 'unreal-engine',
    category: 'Game Development',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/unrealengine/unrealengine-original.svg',
    aliases: ['UE', 'UE5'],
    verified: true,
  },
  {
    id: 'skill_godot',
    name: 'Godot',
    slug: 'godot',
    category: 'Game Development',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/godot/godot-original.svg',
    aliases: ['Godot Engine'],
    verified: true,
  },
  {
    id: 'skill_threejs',
    name: 'Three.js',
    slug: 'threejs',
    category: 'Game Development',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/threejs/threejs-original.svg',
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_phaser',
    name: 'Phaser',
    slug: 'phaser',
    category: 'Game Development',
    logoUrl: null,
    aliases: ['Phaser.js'],
    verified: true,
  },
  {
    id: 'skill_babylonjs',
    name: 'Babylon.js',
    slug: 'babylonjs',
    category: 'Game Development',
    logoUrl: null,
    aliases: [],
    verified: true,
  },
  // ========== BLOCKCHAIN ==========
  {
    id: 'skill_ethereum',
    name: 'Ethereum',
    slug: 'ethereum',
    category: 'Blockchain',
    logoUrl: null,
    aliases: ['ETH'],
    verified: true,
  },
  {
    id: 'skill_solidity',
    name: 'Solidity',
    slug: 'solidity',
    category: 'Blockchain',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/solidity/solidity-original.svg',
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_web3js',
    name: 'Web3.js',
    slug: 'web3js',
    category: 'Blockchain',
    logoUrl: null,
    aliases: ['Web3'],
    verified: true,
  },
  {
    id: 'skill_ethersjs',
    name: 'Ethers.js',
    slug: 'ethersjs',
    category: 'Blockchain',
    logoUrl: null,
    aliases: ['Ethers'],
    verified: true,
  },
  {
    id: 'skill_hardhat',
    name: 'Hardhat',
    slug: 'hardhat',
    category: 'Blockchain',
    logoUrl: null,
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_truffle',
    name: 'Truffle',
    slug: 'truffle',
    category: 'Blockchain',
    logoUrl: null,
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_ipfs',
    name: 'IPFS',
    slug: 'ipfs',
    category: 'Blockchain',
    logoUrl: null,
    aliases: [],
    verified: true,
  },
  // ========== DESIGN TOOLS ==========
  {
    id: 'skill_figma',
    name: 'Figma',
    slug: 'figma',
    category: 'Design',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/figma/figma-original.svg',
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_sketch',
    name: 'Sketch',
    slug: 'sketch',
    category: 'Design',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/sketch/sketch-original.svg',
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_adobexd',
    name: 'Adobe XD',
    slug: 'adobe-xd',
    category: 'Design',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/xd/xd-plain.svg',
    aliases: ['XD'],
    verified: true,
  },
  {
    id: 'skill_storybook',
    name: 'Storybook',
    slug: 'storybook',
    category: 'Design',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/storybook/storybook-original.svg',
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_framer',
    name: 'Framer',
    slug: 'framer',
    category: 'Design',
    logoUrl: null,
    aliases: [],
    verified: true,
  },
  // ========== ANALYTICS ==========
  {
    id: 'skill_googleanalytics',
    name: 'Google Analytics',
    slug: 'google-analytics',
    category: 'Analytics',
    logoUrl: null,
    aliases: ['GA', 'GA4'],
    verified: true,
  },
  {
    id: 'skill_mixpanel',
    name: 'Mixpanel',
    slug: 'mixpanel',
    category: 'Analytics',
    logoUrl: null,
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_amplitude',
    name: 'Amplitude',
    slug: 'amplitude',
    category: 'Analytics',
    logoUrl: null,
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_segment',
    name: 'Segment',
    slug: 'segment',
    category: 'Analytics',
    logoUrl: null,
    aliases: ['Twilio Segment'],
    verified: true,
  },
  {
    id: 'skill_posthog',
    name: 'PostHog',
    slug: 'posthog',
    category: 'Analytics',
    logoUrl: null,
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_hotjar',
    name: 'Hotjar',
    slug: 'hotjar',
    category: 'Analytics',
    logoUrl: null,
    aliases: [],
    verified: true,
  },
  // ========== AUTHENTICATION ==========
  {
    id: 'skill_auth0',
    name: 'Auth0',
    slug: 'auth0',
    category: 'Authentication',
    logoUrl: null,
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_okta',
    name: 'Okta',
    slug: 'okta',
    category: 'Authentication',
    logoUrl: null,
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_firebaseauth',
    name: 'Firebase Auth',
    slug: 'firebase-auth',
    category: 'Authentication',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/firebase/firebase-plain.svg',
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_awscognito',
    name: 'AWS Cognito',
    slug: 'aws-cognito',
    category: 'Authentication',
    logoUrl: null,
    aliases: ['Amazon Cognito'],
    verified: true,
  },
  {
    id: 'skill_clerk',
    name: 'Clerk',
    slug: 'clerk',
    category: 'Authentication',
    logoUrl: null,
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_supabaseauth',
    name: 'Supabase Auth',
    slug: 'supabase-auth',
    category: 'Authentication',
    logoUrl: null,
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_passportjs',
    name: 'Passport.js',
    slug: 'passportjs',
    category: 'Authentication',
    logoUrl: null,
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_nextauthjs',
    name: 'NextAuth.js',
    slug: 'nextauthjs',
    category: 'Authentication',
    logoUrl: null,
    aliases: ['Auth.js'],
    verified: true,
  },
  // ========== PAYMENT ==========
  {
    id: 'skill_stripe',
    name: 'Stripe',
    slug: 'stripe',
    category: 'Payment',
    logoUrl: null,
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_paypal',
    name: 'PayPal',
    slug: 'paypal',
    category: 'Payment',
    logoUrl: null,
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_square',
    name: 'Square',
    slug: 'square',
    category: 'Payment',
    logoUrl: null,
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_braintree',
    name: 'Braintree',
    slug: 'braintree',
    category: 'Payment',
    logoUrl: null,
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_razorpay',
    name: 'Razorpay',
    slug: 'razorpay',
    category: 'Payment',
    logoUrl: null,
    aliases: [],
    verified: true,
  },
  // ========== LOW-CODE/NO-CODE ==========
  {
    id: 'skill_bubble',
    name: 'Bubble',
    slug: 'bubble',
    category: 'Low-Code',
    logoUrl: null,
    aliases: ['Bubble.io'],
    verified: true,
  },
  {
    id: 'skill_webflow',
    name: 'Webflow',
    slug: 'webflow',
    category: 'Low-Code',
    logoUrl: null,
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_retool',
    name: 'Retool',
    slug: 'retool',
    category: 'Low-Code',
    logoUrl: null,
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_zapier',
    name: 'Zapier',
    slug: 'zapier',
    category: 'Low-Code',
    logoUrl: null,
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_airtable',
    name: 'Airtable',
    slug: 'airtable',
    category: 'Low-Code',
    logoUrl: null,
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_n8n',
    name: 'n8n',
    slug: 'n8n',
    category: 'Low-Code',
    logoUrl: null,
    aliases: [],
    verified: true,
  },
  // ========== OTHER TOOLS ==========
  {
    id: 'skill_elasticsearch',
    name: 'Elasticsearch',
    slug: 'elasticsearch',
    category: 'Search',
    logoUrl: null,
    aliases: ['Elastic'],
    verified: true,
  },
  {
    id: 'skill_algolia',
    name: 'Algolia',
    slug: 'algolia',
    category: 'Search',
    logoUrl: null,
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_sonarqube',
    name: 'SonarQube',
    slug: 'sonarqube',
    category: 'Security',
    logoUrl: null,
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_snyk',
    name: 'Snyk',
    slug: 'snyk',
    category: 'Security',
    logoUrl: null,
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_vault',
    name: 'HashiCorp Vault',
    slug: 'vault',
    category: 'Security',
    logoUrl: null,
    aliases: ['Vault'],
    verified: true,
  },
  {
    id: 'skill_bun',
    name: 'Bun',
    slug: 'bun',
    category: 'Runtime',
    logoUrl: null,
    aliases: [],
    verified: true,
  },
  {
    id: 'skill_deno',
    name: 'Deno',
    slug: 'deno',
    category: 'Runtime',
    logoUrl: null,
    aliases: [],
    verified: true,
  },
]

async function main() {
  let created = 0
  let updated = 0

  for (const s of skills) {
    const existed = await prisma.skill.findUnique({ where: { slug: s.slug } })
    await prisma.skill.upsert({
      where: { slug: s.slug },
      create: {
        id: s.id,
        name: s.name,
        slug: s.slug,
        category: s.category ?? undefined,
        logoUrl: s.logoUrl ?? undefined,
        aliases: s.aliases ? JSON.stringify(s.aliases) : undefined,
        verified: s.verified ?? true,
      },
      update: {
        name: s.name,
        category: s.category ?? undefined,
        logoUrl: s.logoUrl ?? undefined,
        aliases: s.aliases ? JSON.stringify(s.aliases) : undefined,
        verified: s.verified ?? true,
      },
    })
    if (existed) updated++
    else created++
  }

  console.log(`Seed completed. Created: ${created}, Updated: ${updated}`)
}

main()
  .catch((e) => {
    console.error(e)
    process.exitCode = 1
  })
  .finally(async () => {
    await prisma.$disconnect()
  })

